### ISSUE TITLE
 Error: cannot import name 'CIFAR10' from 'datasets' 

### ISSUE THREAD

**Issue by TheSunWillRise** [DingfanChen/RelaxLoss#2]
Thanks for the codes.

What is the version of your datasets?

**Comment by DingfanChen** [comment]
Hi,
I've updated some module references in the code. Could you try the new version again?

And in case you still face any errors, could you please provide a minimal reproducible example? E.g., what's the complete command you use? Thanks.

**Comment by TheSunWillRise** [comment]
Hi,
I just run simple command "python main.py", it still raises error "ImportError: cannot import name 'CIFAR10' from 'datasets'".
My 'datasets' package is install from pip and the version is 2.1.0.
I think this error may be because the different version of 'datasets'.

**Comment by DingfanChen** [comment]
Hi,
'datasets' was a python file provided in the code (under 'source/cifar') and there is no need to install other packages. The error is then due to the double occurrence of the 'datasets' module.  
I've renamed the file to avoid conflicts. Please try and see if the issue is resolved. Thanks.

**Comment by TheSunWillRise** [comment]
It works now. Thank you.
