### ISSUE TITLE
File missing in "RelaxLoss/source/nonimage/defense"

### ISSUE THREAD

**Issue by dungpham98** [DingfanChen/RelaxLoss#3]
Hi, Im trying to convert your code to my Jupyter Notebook for reproduction purpose. However in "RelaxLoss/source/nonimage/defense/base.py", there is a line say:

## from datasets import prepare_texas, prepare_purchase

But there are no datasets.py in the folder as well as the function "prepare_texas" and " prepare_purchase", can you please check that or clarify things for me if possible ?

Thank you.

**Comment by DingfanChen** [comment]
Hi, thanks a lot for pointing this out.
I've added the 'source/nonimage/dataset.py' file and modified the reference in 'source/nonimage/run_attacks.py' and 'source/nonimage/defense/base.py' accordingly.

Please use this updated version and let me know if you have any further questions.

Many thanks.

**Comment by dungpham98** [comment]
Thanks, Im able to reproduce the code now.
